version: '3.9'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jopa
      POSTGRES_DB: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    command: bash -c "chown -R postgres:postgres /var/lib/postgresql/data && postgres"
    # change rules to allow usage of volume
  app:
    build: ./
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - db
  redis:
    image: redis:latest
    restart: always
    depends_on:
      - db
