FROM python:3.13-slim

WORKDIR /app/backend

COPY ./requirements.txt ./requirements.txt
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

ENTRYPOINT [ "python3", "./app.py" ]
