version: '3.9'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jopa
      POSTGRES_DB: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  app:
    build: ./
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - db
    volumes:
      - ../frontend:/app/frontend
      - ../backend:/app/backend
    networks:
      - app-network

  redis:
    image: redis:latest
    restart: always
    depends_on:
      - db
    networks:
      - app-network
